### ISSUE TITLE
Publish to deno.land/x

### ISSUE THREAD

**Issue by Kycermann** [rodneylab/parsedown#1]
**Is your feature request related to a problem? Please describe.**
I want to use this with Deno but I don't see it on deno.land/x.

**Describe the solution you'd like**
I'd like this module to be on deno.land/x :)

**Describe alternatives you've considered**
I could compile it from Rust myself but I don't know how to do it.

**Additional context**
Instructions are here: https://deno.land/add_module

**Comment by rodneylab** [comment]
Thanks for feedback Mieszko. That is a nice idea. I have to add more docs too. I will work on this when I get time.

**Comment by rodneylab** [comment]
Hey Mieszko, the module is now live on deno.x: [Parsedown](https://deno.land/x/parsedown@1.3.1). Readme is now updated too.

Thanks for the suggestion. Let me know if you have any issues.

https://github.com/rodneylab/parsedown/commit/8ad1d545a7a185b56ce30d6c0e31d0b560ca66f7
